### ISSUE TITLE
png转换成webp后，子模块的mergeReleaseResources任务报错：java.nio.file.NoSuchFileException。

### ISSUE THREAD

**Issue by opLW** [Mobcase/McImage#86]
- 请教个问题：
子模块的mergeReleaseResources任务报错：java.nio.file.NoSuchFileException。因为子模块要找的图片，已经由原来的.png后缀转换成.webp，所以找不到。
大致报错如：
Caused by: java.nio.file.NoSuchFileException: .../build/intermediates/packaged_res/release/drawable-hdpi-v4/A.png
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixCopyFile.copy(UnixCopyFile.java:548)
	at java.base/sun.nio.fs.UnixFileSystemProvider.copy(UnixFileSystemProvider.java:254)
	at java.base/java.nio.file.Files.copy(Files.java:1294)
	at com.android.utils.FileUtils.copyFile(FileUtils.java:151)
	at com.android.utils.FileUtils.copyFile(FileUtils.java:133)
	at com.android.utils.FileUtils.copyFile(FileUtils.java:116)
	at com.android.ide.common.resources.CopyToOutputDirectoryResourceCompilationService.submitCompile(CopyToOutputDirectoryResourceCompilationService.kt:27)
	at com.android.ide.common.resources.MergedResourceWriter.end(MergedResourceWriter.java:292)

- 出现场景：
android studio上没有问题，jenkins上偶尔会出现上述情况。

- 尝试：
1）因为偶尔出现GC Overhead Limit Exceeded，所以把MaxMetaspaceSize调大，但貌似没有用。
2）猜测可能是多线程导致的，multiThread设置成false，仍会有问题。

**Comment by allen-blue** [comment]
子模块packaged_res 生成了webp 但是工程中没有替换 只有app下的res替换了webp 
有遇到过吗

**Comment by niemj** [comment]
这个解决了么？

**Comment by opLW** [comment]
这个偶现，暂时没有定位出原因。最后我们猜测可能是jenkins打包时，需要压缩图片的project占用太多CPU资源，导致的意外情况。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月20日(星期三) 下午4:20
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [smallSohoSolo/McImage] png转换成webp后，子模块的mergeReleaseResources任务报错：java.nio.file.NoSuchFileException。 (Issue #86)





 
这个解决了么？

**Comment by allen-blue** [comment]
我android studio 上也有问题  jenkins没试

**Comment by niemj** [comment]
我android studio 上没问题， 但jenkins上很容易出现

**Comment by opLW** [comment]
一样的情况。我们最后是AndroidStudio跑一遍，然后保存压缩的图片，jenkins打包时动态替换相应图片。



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年4月20日(星期三) 下午4:40
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; "State ***@***.***&gt;; 
主题: Re: [smallSohoSolo/McImage] png转换成webp后，子模块的mergeReleaseResources任务报错：java.nio.file.NoSuchFileException。 (Issue #86)





 
我android studio 上没问题， 但jenkins上很容易出现
